Models/Complaint.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace DCNE_Cake.Models
{
    public class Complaint
    {
        [Key]
        public int ComplaintID { get; set; }

        [Required]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Message")]
        public string ComplaintBox { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Date")]
        public DateTime ComplaintDate { get; set; }

        [ForeignKey("Location")]
        public int LocationID { get; set; }

        [ForeignKey("ComplaintCategory")]
        public int ComplaintCatId { get; set; }

        //[ForeignKey("UserProfile")]
        //public int UserId { get; set; }

        [ForeignKey("Product")]
        public int ProductId { get; set; }

        //Navigational Properties
        public virtual ComplaintCategory ComplaintCategory { get; set; }
        public virtual Product Product { get; set; }
        public virtual Location Location { get; set; }
        //public virtual UserProfile UserProfile { get; set; }
    }
}

Models/ViewModels/ComplaintViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DCNE_Cake.Models.ViewModels
{
    public class ComplaintViewModel
    {
        public Complaint Complaint { get; set; }

        public ComplaintViewModel(Complaint complaint)
        {
            this.Complaint = complaint;
        }
    }
}

Controllers/ComplaintController.cs
using DCNE_Cake.Filters;
using DCNE_Cake.Models;
using DCNE_Cake.Models.ViewModels;
using DCNE_Cake.Repository;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;
using WebMatrix.WebData;

namespace DCNE_Cake.Controllers
{
    [InitializeSimpleMembership]
    public class ComplaintController : Controller
    {
        private UnitOfWork unitOfWork = new UnitOfWork();
        //
        // GET: /Complaint/

        public ActionResult Index(string sortOrder, string searchString)
        {
            return SortingFilteringSearchingAndPaging(sortOrder, searchString);
        }

       

        //
        // GET: /Complaint/Details/5

        public ActionResult Details(int id)
        {
            var result = unitOfWork.ComplaintRepository.GetComplaintById(id);
            return View(result);
        }

        //
        // GET: /Complaint/Create

        public ActionResult Create()
        {
            //TODO : populate drop down list for
            //Location and complaintCategory

            ViewBag.LocationId = new SelectList(unitOfWork.LocationRepository.GetLocation(), "LocationID", "LocationName");
            ViewBag.ComplaintCateId = new SelectList(unitOfWork.ComplaintCategoryRepository.GetComplaintCategory(), "ComplaintCatId", "ComplaintCatName");
            ViewBag.ProductId = new SelectList(unitOfWork.ProductRepository.GetProducts(), "ProductId", "Name");
            return View();
        }

        //
        // POST: /Complaint/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Complaint complaint)
        {
            //Set the time when the form is submitted so modelstate will be valid
            complaint.ComplaintDate = Convert.ToDateTime(DateTime.Now.Date.ToShortDateString());
            //complaint.UserId = WebSecurity.GetUserId(User.Identity.Name);
            try
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.ComplaintRepository.InsertComplaint(complaint);
                    unitOfWork.Save();
                    //return RedirectToAction("Message");
                    return RedirectToAction("Message", new { id = complaint.ComplaintID });

                    //return RedirectToAction("Index");
                }
                else
                {
                    //TODO : populate drop down list
                    ViewBag.LocationId = new SelectList(unitOfWork.LocationRepository.GetLocation(), "LocationID", "LocationName");
                    ViewBag.ComplaintCateId = new SelectList(unitOfWork.ComplaintCategoryRepository.GetComplaintCategory(), "ComplaintCatId", "ComplaintCatName");
                    ViewBag.ProductId = new SelectList(unitOfWork.ProductRepository.GetProducts(), "ProductId", "Name");
                    return View();
                }
               
            }
            catch (DataException ex)
            {
                ModelState.AddModelError("", "Unable to save changes. Try again, if problem persists see your administrator");
                return View();
            }
        }

        [HttpGet]
        public ActionResult Message(int id)
        {
            Complaint cmp =  unitOfWork.ComplaintRepository.GetComplaintById(id);
            return PartialView("_SuccessMessage", cmp);
        }
        //
        // GET: /Complaint/Edit/5

        public ActionResult Edit(int id)
        {
            var complaint = unitOfWork.ComplaintRepository.GetComplaintById(id);
            if (complaint == null)
            {
                return HttpNotFound(statusDescription: "The record does not exist");
            }
            /* var selectedCompCate = from c in unitOfWork.ComplaintCategoryRepository.GetComplaintCategory()
                            where c.ComplaintCatId == id
                            select c.ComplaintCatName;

             var selectedLocation = from c in unitOfWork.LocationRepository.GetLocation()
                                    where c.LocationID == id
                                    select c.LocationName;*/

            //TODO : populate drop down list for Location and ComplaintCategory

            ViewBag.LocationId = new SelectList(unitOfWork.LocationRepository.GetLocation(), "LocationID", "LocationName", complaint.LocationID);
            ViewBag.ComplaintCateId = new SelectList(unitOfWork.ComplaintCategoryRepository.GetComplaintCategory(), "ComplaintCatId", "ComplaintCatName", complaint.ComplaintCatId);

            return View(complaint);
        }

        //
        // POST: /Complaint/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Complaint complaint)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    unitOfWork.ComplaintRepository.UpdateComplaint(complaint);
                    unitOfWork.Save();
                    return RedirectToAction("Index");
                }
            }
            catch (DataException ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            ViewBag.LocationId = new SelectList(unitOfWork.LocationRepository.GetLocation(), "LocationID", "LocationName", complaint.LocationID);
            ViewBag.ComplaintCateId = new SelectList(unitOfWork.ComplaintCategoryRepository.GetComplaintCategory(), "ComplaintCatId", "ComplaintCatName", complaint.ComplaintCatId);

            return View(complaint);
        }

        //Sample code for ViewModel
        public ActionResult EditTwo(int id)
        {
            var complaints = unitOfWork.ComplaintRepository.GetComplaintById(id);
            var complaintViewModel = new ComplaintViewModel(complaints);
            return View(complaintViewModel);
        }
        //
        // GET: /Complaint/Delete/5

        public ActionResult Delete(int id)
        {
            unitOfWork.ComplaintRepository.GetComplaintById(id);
            return View();
        }

        //
        // POST: /Complaint/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }



        protected override void Dispose(bool disposing)
        {
            unitOfWork.Dispose();
            base.Dispose(disposing);
        }

        //helpers
        #region

        //General Filtering, Sorting and Paging
        private ViewResult SortingFilteringSearchingAndPaging(string sortOrder, string searchString)
        {
            ViewBag.messageSortParam = String.IsNullOrEmpty(sortOrder) ? "message_desc" : "";
            ViewBag.Category = sortOrder == "Category" ? "Category_desc" : "Category";
            ViewBag.Location = sortOrder == "Location" ? "Location_desc" : "Location";

            var complaints = unitOfWork.ComplaintRepository.GetComplaints();

            if (!string.IsNullOrEmpty(searchString))
            {
                //Linq query
                complaints = from c in complaints
                             where c.ComplaintBox.ToLower().Contains(searchString.ToLower()) || c.ComplaintCategory.ComplaintCatName.ToLower().Contains(searchString.ToLower())
                             || c.Location.LocationName.ToLower().Contains(searchString.ToLower())
                             select c;
            }
            switch (sortOrder)
            {
                case "message_desc":
                    complaints = complaints.OrderByDescending(s => s.ComplaintBox);
                    break;
                case "Category":
                    complaints = complaints.OrderBy(s => s.ComplaintCategory.ComplaintCatName);
                    break;
                case "Category_desc":
                    complaints = complaints.OrderByDescending(s => s.ComplaintCategory.ComplaintCatName);
                    break;
                case "Location":
                    complaints = complaints.OrderBy(s => s.Location.LocationName);
                    break;
                case "Location_desc":
                    complaints = complaints.OrderByDescending(s => s.Location.LocationName);
                    break;
                default:
                    complaints = complaints.OrderBy(s => s.ComplaintDate);
                    break;
            }
            return View(complaints);
        }


        //Filter by Date
        private ViewResult FilterByDate(string searchString)
        {
            var complaints = unitOfWork.ComplaintRepository.GetComplaints();
            if (!string.IsNullOrEmpty(searchString))
            {
                //Linq query
                complaints = from c in complaints
                             where c.ComplaintDate.ToString().Contains(searchString)
                             select c;
            }
            return View(complaints);
        }

        //Filter by Location
        private ViewResult FilterByLocation(string searchString)
        {
            var complaints = unitOfWork.ComplaintRepository.GetComplaints();
            if (!string.IsNullOrEmpty(searchString))
            {
                complaints = from c in complaints
                             where c.Location.LocationName.ToLower().Contains(searchString.ToLower())
                             select c;
            }
            return View(complaints);
        }

        //Filter by Category
        private ViewResult FilterByCategory(string searchString)
        {
            var complaints = unitOfWork.ComplaintRepository.GetComplaints();
            if (!string.IsNullOrEmpty(searchString))
            {

Views/Complaint/ComplaintView.cshtml
@model DCNE_Cake.Models.Complaint

@{
    ViewBag.Title = "ComplaintView";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}

<h2>ComplaintView</h2>

<fieldset>
    <legend>Complaint</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ComplaintBox)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ComplaintBox)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ComplaintDate)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ComplaintDate)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.LocationID)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LocationID)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.ComplaintCatId)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ComplaintCatId)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ComplaintID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Complaint/Create.cshtml
@model DCNE_Cake.Models.Complaint

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}

<div id="result">
    @using (Ajax.BeginForm("Create", "Complaint", 
        new AjaxOptions {
            Confirm = "Are you sure you want to submit?",
            HttpMethod = "POST",
            InsertionMode = System.Web.Mvc.Ajax.InsertionMode.Replace,
            LoadingElementId = "loadingPhoto",
            UpdateTargetId = "result"
        },
        new { @class = "form-horizontal", id = "complaintForm" }))
    {
        @Html.ValidationSummary(true)
        @Html.AntiForgeryToken()

        <div class="row">
            <div class="col-md-6">
                <div class="page-header">
                    <h2>Complaint</h2>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.ComplaintBox, htmlAttributes: new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.TextAreaFor(m => m.ComplaintBox, htmlAttributes: new { @class = "form-control", placeholder = "What's your complaint", id = "inputMessage" })
                        @Html.ValidationMessageFor(m => m.ComplaintBox, "", htmlAttributes: new { @class = "has-error text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.ComplaintCategory.ComplaintCatName, htmlAttributes: new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.ComplaintCatId, ViewBag.ComplaintCateId as SelectList, "--Select Category--", htmlAttributes: new { @class = "form-control", id = "inputCate" })
                        @Html.ValidationMessageFor(m => m.ComplaintCategory.ComplaintCatName, "", htmlAttributes: new { @class = "has-error text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(m => m.Location.LocationName, htmlAttributes: new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.LocationID, ViewBag.LocationId as SelectList, "--Select Location--", htmlAttributes: new { @class = "form-control", id = "inputLocation" })
                        @Html.ValidationMessageFor(m => m.Location.LocationName, "", htmlAttributes: new { @class = "has-error text-danger"})
                    </div>
                </div>

                <div class="form-group">
                    @Html.Label("", "Product", htmlAttributes: new { @class = "col-md-2 control-label" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.ProductId, ViewBag.ProductId as SelectList, "--Select Location--", htmlAttributes: new { @class = "form-control", id = "inputProduct" })
                        @Html.ValidationMessageFor(m => m.Product.Name, "", htmlAttributes: new { @class = "has-error text-danger"})
                    </div>
                </div>

                <div class="col-md-10 col-md-offset-2">
                    <!--Trigger Modal-->
                    <button type="submit" class="btn btn-primary" id="btnSubmit">Create</button>
                    @*@Html.ActionLink("Back", "Index", "Complaint", routeValues: null, htmlAttributes: new { @class = "btn btn-warning" })*@
                </div>
            </div>

            <div class="col-md-3">
                <img src="~/Images/loading.gif" id="loadingPhoto" style="display: none" class="img-responsive" width="40" />
            </div>
        </div>
        
        <!--Modal -->
        @*<div class="modal fade" id="myModal">
            <div class="modal-dialog modal-sm">
                <div class="modal-content">
                    <!--Modal Header-->
                    <div class="modal-header">
                        <h4 class="modal-title">Complaint</h4>
                    </div>
                    <!--Modal Body-->
                    <div class="modal-body text-justify">
                        <h3>Your message has been sent</h3> 
                    </div>
                    <!--Modal footer-->
                    <div class="modal-footer">
                        @Html.ActionLink("Done", "Index", "Home", routeValues: null, htmlAttributes: new { @class = "btn btn-success" })
                        <button type="button" class="btn btn-success">Save</button>
                        <button data-dismiss="modal" type="button" class="btn btn-danger">Close</button>
                    </div>
                </div>
            </div>
        </div>*@
        <!--Modal End-->
    }
</div>

@*<script>

    $(document).ready(function () {

        //$('#complaintForm').submit(function () {
        //    $('#myModal').modal('show');
        //})
        

        /*$('.btn-bootstrap-dialog').click(function () {
            var url = $('#bootstrapDialog').data('url');

            $.get(url, function (data) {
                $('#bootstrapDialog').html(data);

                $('#bootstrapDialog').modal('show');
            });
        });*/
    });

    function TriggerModal() {
       
        $('#myModal').modal('show');
    }
</script>*@

Views/Complaint/Details.cshtml
@model DCNE_Cake.Models.Complaint

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}

<div class="row">
    <div class="col-md-4">
        <div class="page-header">
            <h2>Details</h2>
        </div>

        <!--using list group-->
        <div class="list-group">
            <div class="list-group-item">
               @Html.DisplayNameFor(model => model.ComplaintBox) : @Html.DisplayFor(model => model.ComplaintBox)
            </div>

            <div class="list-group-item">
                @Html.DisplayNameFor(model => model.ComplaintCategory.ComplaintCatName) : @Html.DisplayFor(m => m.ComplaintCategory.ComplaintCatName)
            </div>

            <div class="list-group-item">
                @Html.DisplayNameFor(model => model.ComplaintDate) : @Html.DisplayFor(model => model.ComplaintDate)
            </div>

            <div class="list-group-item">
                @Html.DisplayNameFor(model => model.Location.LocationName) : @Html.DisplayFor(model => model.Location.LocationName)
            </div>
            
            <div class="list-group-item">
                @Html.ActionLink("Back", "Index", "Complaint", new{ id = Model.ComplaintID, @class = "btn btn-danger"})
            </div>
        </div>
    </div>
</div>

Views/Complaint/Edit.cshtml
@model DCNE_Cake.Models.Complaint

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}

@using (Html.BeginForm("Edit", "complaint", FormMethod.Post, htmlAttributes: new { @class = "form-horizontal" }))
{
    @Html.ValidationSummary(true)
    @Html.AntiForgeryToken()

    @Html.HiddenFor(model => model.ComplaintID)

    <div class="row">
        <div class="col-md-6">
            <div class="page-header">
                <h2>Edit</h2>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.ComplaintBox, htmlAttributes: new{ @class = "col-md-2 control-label"})
                <div class="col-md-10">
                  @Html.TextAreaFor(m => m.ComplaintBox, htmlAttributes: new{ @class = "form-control"})
                </div>
            </div>
            
            <div class="form-group">
                @Html.LabelFor(m => m.ComplaintCategory.ComplaintCatName, htmlAttributes: new{ @class = "col-md-2 control-label"})
                <div class="col-md-10">
                    @Html.DropDownList("ComplaintCateId", ViewBag.ComplaintCateId as SelectList, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(m => m.Location.LocationName, htmlAttributes: new{ @class = "col-md-2 control-label"})
                <div class="col-md-10">
                    @Html.DropDownList("LocationId", ViewBag.LocationId as SelectList, htmlAttributes: new { @class = "form-control" })
                </div>
            </div>
            <div class="col-md-10 col-md-offset-2">
                <button type="submit" class="btn btn-primary ">Save</button>
                @Html.ActionLink("Back", "Index", "complaint", routeValues: null, htmlAttributes: new { @class = "btn btn-warning" })
            </div>
        </div>
    </div>
    
}

Views/Complaint/EditTwo.cshtml
@model DCNE_Cake.Models.ViewModels.ComplaintViewModel

@{
    ViewBag.Title = "EditTwo";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}

<h2>EditTwo</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>ComplaintViewModel</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Complaint.ComplaintBox)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Complaint.ComplaintBox)
            @Html.ValidationMessageFor(model => model.Complaint.ComplaintBox)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Complaint.ComplaintDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Complaint.ComplaintDate)
            @Html.ValidationMessageFor(model => model.Complaint.ComplaintDate)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Complaint.Location.LocationName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Complaint.Location.LocationName)
            @Html.ValidationMessageFor(model => model.Complaint.Location.LocationName)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Complaint/Index.cshtml
@model IEnumerable<DCNE_Cake.Models.Complaint>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_SiteLayout.cshtml";
}

<div class="row">
       <div class="col-md-5 col-md-offset-3 col-sm-7 col-sm-offset-2">
        @using (Html.BeginForm("Index", "Complaint", FormMethod.Get, htmlAttributes: new { @class = "form-inline" }))
        {
            <div class="well well-sm">
                @Html.DisplayName("Find complaint"): <div class="form-group">@Html.TextBox("searchString", "", htmlAttributes: new { @class = "form-control", placeholder = "Search by Location, Category" })</div>
                <button type="submit" class="btn btn-primary">Search</button>
            </div>
        }
    </div>
</div>

@if(Request.IsAuthenticated && HttpContext.Current.User.IsInRole("Admin"))
{
    @Html.ActionLink("Create New", "Create")
}

    @Html.ActionLink("GeneratePDF", "GeneratePDF", "Complaint", routeValues: null, htmlAttributes: new{ @class = "btn btn-info list-float marg" })
<table class="table table-bordered table-stripped">
    <tr>
        <th>
            @Html.ActionLink("Message","Index", new{sortOrder = ViewBag.messageSortParam})
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ComplaintDate)
        </th>
        <th>
            @Html.ActionLink("Location", "Index", new { sortOrder = ViewBag.Location })
        </th>
        <th>
            @Html.ActionLink("Category", "Index", new {sortOrder = ViewBag.Category })
        </th>
        <th>Manage</th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
             @Html.DisplayFor(modelItem => item.ComplaintBox)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ComplaintDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Location.LocationName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ComplaintCategory.ComplaintCatName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ComplaintID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ComplaintID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ComplaintID })
        </td>
    </tr>
}

</table>

Views/Complaint/_SuccessMessage.cshtml
@model DCNE_Cake.Models.Complaint

<h3 class="text-center">Your message has been sent</h3>



<div class="modal-dialog">
    <div class="modal-content">
        <div class="modal-header">
            @*<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>*@
            <h4 class="modal-title" id="myModal-label">Complaint Lodged</h4>
        </div>
        <div class="modal-body">

            <div class="list-group">
                <div class="list-group-item">
                    <strong>@Html.DisplayNameFor(model => model.ComplaintBox) : </strong><span >@Html.DisplayFor(model => model.ComplaintBox)</span>
                </div>
                <div class="list-group-item">
                    <strong>@Html.DisplayNameFor(model => model.ComplaintCategory.ComplaintCatName) : </strong><span >@Html.DisplayFor(model => model.ComplaintCategory.ComplaintCatName)</span>
                </div>
                <div class="list-group-item">
                    <strong>@Html.DisplayNameFor(model => model.Location.LocationName) :</strong> <span >@Html.DisplayFor(model => model.Location.LocationName)</span>
                </div>
                <div class="list-group-item">
                    <strong>Product :</strong> <span class="list-float">@Html.DisplayFor(model => model.Product.Name)</span>
                </div>
            </div>

            @*<table>
                <tr>
                    <td>@Html.DisplayNameFor(m => m.ComplaintBox)</td>
                    <td>@Html.ValueFor(m => m.ComplaintBox)</td>
                </tr>
            </table>*@
        </div>
        <div class="modal-footer">
             @Html.ActionLink("Done", "Index", "Home", routeValues: null, htmlAttributes: new { @class = "btn btn-success"})
            @*<button class="btn btn-primary" id="btnOK" onclick="">OK</button>
            <button class="btn btn-default" data-dismiss="modal" id="btnCancel">Cancel</button>*@
        </div>
    </div>
</div>